---
- hosts: all

  vars_prompt:
    - name: "NroPrueba"
      prompt: "Ingrese Nro de Prueba:"
      default: "1"
      private: no

  tasks:
    - include_role:
        name: multi_Pruebas
    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

